default_data: &default
  data_path:
    default: null
    help: "Set null to run locally on your machine (data is located in data folder outside the project folder by 1 level),
    otherwise set the global path"
  subjects_list:
    default: [  1 , 2 , 3 , 4 , 5 ,  6 , 7 , 8 , 9 ,10 ,11, 12, 13, 14 ,15 ,16 ,17, 18, 19, 20, 21, 22, 23 ,24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37 ,38 ] #,39, 40 ,41, 42, 43 ,44, 45 ,46 ,47 ] #,48, 49, 50, 51, 52, 53, 54, 55, 56, 57] #, 58, 59, 60, 61]
    help:
  sessions_list:
    default: [ [4,5,6,7,8,10,11,12 ] ,[4,5,6,7,8,10,11,12 ] ,[4,5,6,7,8,10,11,12 ] ,[4,5,6,7,8,10,11,12 ] ,[4,5,6,7,8,10,11,12 ] ,[4,5,6,7,8,10,11,12 ] ,[4,5,6,7,8,10,11,12 ] ,[4,5,6,7,8,10,11,12 ] ,[4,5,6,7,8,10,11,12 ] ,[4,5,6,7,8,10,11,12 ] ,[4,5,6,7,8,10,11,12 ] ,[4,5,6,7,8,10,11,12 ] ,[4,5,6,7,8,10,11,12 ] ,[4,5,6,7,8,10,11,12 ] ,[4,5,6,7,8,10,11,12 ] ,[4,5,6,7,8,10,11,12 ] ,[4,5,6,7,8,10,11,12 ] ,[4,5,6,7,8,10,11,12 ] ,[4,5,6,7,8,10,11,12 ] ,[4,5,6,7,8,10,11,12 ] ,[4,5,6,7,8,10,11,12 ] ,[4,5,6,7,8,10,11,12 ] ,[4,5,6,7,8,10,11,12 ] ,[4,5,6,7,8,10,11,12 ] ,[4,5,6,7,8,10,11,12 ] ,[4,5,6,7,8,10,11,12 ] ,[4,5,6,7,8,10,11,12 ] ,[4,5,6,7,8,10,11,12 ] ,[4,5,6,7,8,10,11,12 ] ,[4,5,6,7,8,10,11,12 ] ,[4,5,6,7,8,10,11,12 ] ,[4,5,6,7,8,10,11,12 ] ,[4,5,6,7,8,10,11,12 ] ,[4,5,6,7,8,10,11,12 ] ,[4,5,6,7,8,10,11,12 ] ,[4,5,6,7,8,10,11,12 ] ,[4,5,6,7,8,10,11,12 ] ,[4,5,6,7,8,10,11,12 ] ] #,[4,5,6,7,8,10,11,12 ] ,[4,5,6,7,8,10,11,12 ] ,[4,5,6,7,8,10,11,12 ] ,[4,5,6,7,8,10,11,12 ] ,[4,5,6,7,8,10,11,12 ] ,[4,5,6,7,8,10,11,12 ] ,[4,5,6,7,8,10,11,12 ] ,[4,5,6,7,8,10,11,12 ] ,[4,5,6,7,8,10,11,12 ] ] #,[4,5,6,7,8,10,11,12 ] ,[4,5,6,7,8,10,11,12 ] ,[4,5,6,7,8,10,11,12 ] ,[4,5,6,7,8,10,11,12 ] ,[4,5,6,7,8,10,11,12 ] ,[4,5,6,7,8,10,11,12 ] ,[4,5,6,7,8,10,11,12 ] ,[4,5,6,7,8,10,11,12 ] ,[4,5,6,7,8,10,11,12 ] ,[4,5,6,7,8,10,11,12 ]] #,[4,5,6,7,8,10,11,12 ] ,[4,5,6,7,8,10,11,12 ] ,[4,5,6,7,8,10,11,12 ] ,[4,5,6,7,8,10,11,12 ]  ]
    help:
  task_type:
    default: "LR"
    help:
  time_interval:
    default: [ 2000, 7000 ]
    help:
  reshape_type:
    default: "slice"
    help:
  merge_sessions:
    default: True
    help:
  norm_type:
    default: "std"
    help:
  norm_axis:
    default: 2
    help:
  reshape_axes:
    default: null
    help: "it must be a tuple or list which contains a permutation of [0,1,..,N-1] to perform reshaping (see numpy.transpose).
    null means keeping the same shape."
  device:
    default: "cuda"
    help:
  non_blocking:
    default: true
    help: Non-blocking property to speed up data loading
  enable_testing:
    default: False
    help:
  test_subjects_list:
    default: [ 1 ]
    help:
  test_sessions_list:
    default: [ [ 1,2,3 ] ]
    help:
  train_dev_test_split:
    default: [ 0.8, 0.2, 0.0 ]
    help:
  num_epochs:
    default: 500
    help: Number of epochs
  max_training_time:
    default: 0
    help: Maximum training time in hours. Disabled by default (default=0)
  seed:
    default: 1234
    help: Seed applied to all random generators
  batch_size:
    default: 32
    help: Size of the training batch

debug_data:
  <<: *default
  data_path: null
  subjects_list: [ 1 ]
  sessions_list: [ [ 1 ] ]
  num_epochs: 10

tune_data:
  <<: *default
  num_epochs: 100
  time_interval: [ 2000, 7000 ]
  subjects_list: [ 1,2,3,4,5,6,7,8,9,10 ]
  sessions_list: [ [ 1,3,5,7,9 ] , [ 1,3,5,7,9 ], [ 2,3,6,7 ], [ 1,3,6,7,9 ], [ 2,3,5,7 ],[ 2,3,5,7 ],[ 1,3,5,7,9 ],[ 1,3,5,7,9 ],[ 1,3,5,7,9 ],[ 1,3,5,7,9 ] ]

train_data:
  <<: *default
  num_epochs: 1000
  batch_size: 64
  subjects_list: [ 11,20,30 ]
  sessions_list: [ [ 1,3,5,7,9 ] , [ 1,3,5,7,9 ], [ 2,3,6,7 ], [ 1,3,6,7,9 ], [ 2,3,5,7 ],[ 2,3,5,7 ],[ 1,3,5,7,9 ],[ 1,3,5,7,9 ],[ 1,3,5,7,9 ],[ 1,3,5,7,9 ] ]
  norm_type: "minmax"
  norm_axis: 0

test_data:
  <<: *default
  time_interval: [ 2000, 7000 ]
  subjects_list: [ 1,2,3,4,5,6,7,8,9,10 ]
  sessions_list: [ [ 4,10 ] , [ 4,10 ], [ 4,10 ], [ 2,4 ], [ 4,8 ],[ 4,8 ],[ 2,4 ],[ 2,4 ],[ 2,4 ],[ 2,4 ] ]
#  subjects_list: [ 11,20,30 ]
#  sessions_list: [ [ 4,10 ] , [ 4,10 ], [ 4,10 ] ]
#  subjects_list: [ 1 ]
#  sessions_list: [ [ 1 ] ]
  norm_type: "std"
  norm_axis: 1